language: python
branches:
  only:
    - master
addons:
  apt_packages:
    - pandoc
install:
  - pip install -r build/requirements.txt
script:
  - make
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
