language: python
branches:
  only:
    - master
before_install:
  - curl -fLo /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.4/pandoc-2.4-1-amd64.deb
  - sudo dpkg -i /tmp/pandoc.deb
install:
  - pip install -r build/requirements.txt
script:
  - make
before_deploy:
  - rm -r build
  - rm -r styles/*.scss
  - rm .gitignore
  - rm .travis.yml
  - rm Makefile
  - rm styles/preprint.css.map
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
