language: r
sudo: false
pandoc_version: 2
branches:
  only:
    - master
install:
  - pip install -r build/requirements.txt
script:
  - make
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
